/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "FileReadWrite.h"

bool_t
xdr_DATA (XDR *xdrs, DATA *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->buffer, MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->moreData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_READ_ARGS (XDR *xdrs, READ_ARGS *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, 256))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->offset))
		 return FALSE;
	return TRUE;
}
