/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILEREADWRITE_H_RPCGEN
#define _FILEREADWRITE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_LEN 104857600

struct DATA {
	int length;
	char buffer[MAX_LEN];
	bool_t moreData;
};
typedef struct DATA DATA;

struct READ_ARGS {
	char *filename;
	long offset;
};
typedef struct READ_ARGS READ_ARGS;

#define FILEREADWRITE 0x2070804
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define read 1
extern  DATA * read_1(READ_ARGS *, CLIENT *);
extern  DATA * read_1_svc(READ_ARGS *, struct svc_req *);
extern int filereadwrite_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define read 1
extern  DATA * read_1();
extern  DATA * read_1_svc();
extern int filereadwrite_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_DATA (XDR *, DATA*);
extern  bool_t xdr_READ_ARGS (XDR *, READ_ARGS*);

#else /* K&R C */
extern bool_t xdr_DATA ();
extern bool_t xdr_READ_ARGS ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILEREADWRITE_H_RPCGEN */
