#!/bin/bash

# implement linux du command in bash

for dir in "$@"
do
  subdircount=0
  filecount=0
  echo "===$dir information==="
  subdir="$(ls -a $dir)"
  for file in $subdir
  do
    if [ -d $dir/$file ] && [ $file != "." ] && [ $file != ".." ]; then
      subdircount=$((subdircount + 1))
    fi
    if [ -f $dir/$file ]; then
      filecount=$((filecount + 1))
    fi
  done
  echo "Number of subdirs: $subdircount"
  echo "Number of files: $filecount"
  echo "List of zero length files:"
  echo "--------------------------"
  zerofile="$(find $dir -size 0)"
  for file in $zerofile
  do
    echo $file
  done
  echo "--------------------------"
  diskuse="$(du -sh $dir)"
  set -- $diskuse
  echo "Disk use: $1"
  echo "======================="
done
